- name: Install base system
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - xubuntu-desktop
    - firefox
    - unzip
    - dialog
    - xmlstarlet

